spring:
    application:
        name: batch-users
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: org.postgresql.Driver
        hikari:
            minimum-idle: 10
            maximum-pool-size: 10
            idle-timeout: 600000
            max-lifetime: 1800000
            connection-timeout: 30000
            pool-name: HikariConnPool
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
    rabbitmq:
        host: ${SPRING_RABBITMQ_HOST}
        port: ${SPRING_RABBITMQ_PORT}
        username: ${RABBITMQ_DEFAULT_USER}
        password: ${RABBITMQ_DEFAULT_PASS}

logging:
    level:
        root: ${LOGGING_LEVEL_ROOT}